// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        vX.Y.Z
// source: api/shortener.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URLShortenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *URLShortenRequest) Reset() {
	*x = URLShortenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shortener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLShortenRequest) ProtoMessage() {}

func (x *URLShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLShortenRequest.ProtoReflect.Descriptor instead.
func (*URLShortenRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *URLShortenRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type URLShortenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *URLShortenResponse) Reset() {
	*x = URLShortenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shortener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLShortenResponse) ProtoMessage() {}

func (x *URLShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLShortenResponse.ProtoReflect.Descriptor instead.
func (*URLShortenResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *URLShortenResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type URLExpandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *URLExpandRequest) Reset() {
	*x = URLExpandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shortener_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLExpandRequest) ProtoMessage() {}

func (x *URLExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLExpandRequest.ProtoReflect.Descriptor instead.
func (*URLExpandRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *URLExpandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type URLExpandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *URLExpandResponse) Reset() {
	*x = URLExpandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shortener_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLExpandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLExpandResponse) ProtoMessage() {}

func (x *URLExpandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLExpandResponse.ProtoReflect.Descriptor instead.
func (*URLExpandResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *URLExpandResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type UserURLsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url []*URLData `protobuf:"bytes,1,rep,name=url,proto3" json:"url,omitempty"`
}

func (x *UserURLsResponse) Reset() {
	*x = UserURLsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shortener_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLsResponse) ProtoMessage() {}

func (x *UserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURLsResponse.ProtoReflect.Descriptor instead.
func (*UserURLsResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *UserURLsResponse) GetUrl() []*URLData {
	if x != nil {
		return x.Url
	}
	return nil
}

type URLData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl    string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl string `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (x *URLData) Reset() {
	*x = URLData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shortener_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLData) ProtoMessage() {}

func (x *URLData) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLData.ProtoReflect.Descriptor instead.
func (*URLData) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *URLData) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *URLData) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

var File_api_shortener_proto protoreflect.FileDescriptor

func buildFileDesc() []byte {
	strp := func(s string) *string { return &s }
	i32p := func(i int32) *int32 { return &i }

	// Build a valid FileDescriptorProto at init time.
	// This keeps the repo self-contained (no protoc in CI), while still
	// providing correct protobuf descriptors for reflection and codecs.
	f := &descriptorpb.FileDescriptorProto{
		Syntax:  strp("proto3"),
		Name:    strp("api/shortener.proto"),
		Package: strp("shortener"),
		Dependency: []string{
			"google/protobuf/empty.proto",
		},
		Options: &descriptorpb.FileOptions{GoPackage: strp("github.com/Bekw/go-musthave-shortener/internal/grpcapi/pb;pb")},
		MessageType: []*descriptorpb.DescriptorProto{
			{
				Name: strp("URLShortenRequest"),
				Field: []*descriptorpb.FieldDescriptorProto{{
					Name:     strp("url"),
					Number:   i32p(1),
					Label:    descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
					Type:     descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
					JsonName: strp("url"),
				}},
			},
			{
				Name: strp("URLShortenResponse"),
				Field: []*descriptorpb.FieldDescriptorProto{{
					Name:     strp("result"),
					Number:   i32p(1),
					Label:    descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
					Type:     descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
					JsonName: strp("result"),
				}},
			},
			{
				Name: strp("URLExpandRequest"),
				Field: []*descriptorpb.FieldDescriptorProto{{
					Name:     strp("id"),
					Number:   i32p(1),
					Label:    descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
					Type:     descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
					JsonName: strp("id"),
				}},
			},
			{
				Name: strp("URLExpandResponse"),
				Field: []*descriptorpb.FieldDescriptorProto{{
					Name:     strp("result"),
					Number:   i32p(1),
					Label:    descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
					Type:     descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
					JsonName: strp("result"),
				}},
			},
			{
				Name: strp("UserURLsResponse"),
				Field: []*descriptorpb.FieldDescriptorProto{{
					Name:     strp("url"),
					Number:   i32p(1),
					Label:    descriptorpb.FieldDescriptorProto_LABEL_REPEATED.Enum(),
					Type:     descriptorpb.FieldDescriptorProto_TYPE_MESSAGE.Enum(),
					TypeName: strp(".shortener.URLData"),
					JsonName: strp("url"),
				}},
			},
			{
				Name: strp("URLData"),
				Field: []*descriptorpb.FieldDescriptorProto{
					{
						Name:     strp("short_url"),
						Number:   i32p(1),
						Label:    descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:     descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
						JsonName: strp("shortUrl"),
					},
					{
						Name:     strp("original_url"),
						Number:   i32p(2),
						Label:    descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:     descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
						JsonName: strp("originalUrl"),
					},
				},
			},
		},
		Service: []*descriptorpb.ServiceDescriptorProto{
			{
				Name: strp("ShortenerService"),
				Method: []*descriptorpb.MethodDescriptorProto{
					{
						Name:       strp("ShortenURL"),
						InputType:  strp(".shortener.URLShortenRequest"),
						OutputType: strp(".shortener.URLShortenResponse"),
					},
					{
						Name:       strp("ExpandURL"),
						InputType:  strp(".shortener.URLExpandRequest"),
						OutputType: strp(".shortener.URLExpandResponse"),
					},
					{
						Name:       strp("ListUserURLs"),
						InputType:  strp(".google.protobuf.Empty"),
						OutputType: strp(".shortener.UserURLsResponse"),
					},
				},
			},
		},
	}

	b, err := proto.Marshal(f)
	if err != nil {
		panic(err)
	}
	return b
}

var file_api_shortener_proto_rawDesc = buildFileDesc()

var (
	file_api_shortener_proto_rawDescOnce sync.Once
	file_api_shortener_proto_rawDescData = file_api_shortener_proto_rawDesc
)

func file_api_shortener_proto_rawDescGZIP() []byte {
	file_api_shortener_proto_rawDescOnce.Do(func() {
		file_api_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_shortener_proto_rawDescData)
	})
	return file_api_shortener_proto_rawDescData
}

var (
	file_api_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
	file_api_shortener_proto_goTypes  = []interface{}{
		(*URLShortenRequest)(nil),
		(*URLShortenResponse)(nil),
		(*URLExpandRequest)(nil),
		(*URLExpandResponse)(nil),
		(*UserURLsResponse)(nil),
		(*URLData)(nil),
		(*emptypb.Empty)(nil),
	}
)

var file_api_shortener_proto_depIdxs = []int32{
	5, // 0: shortener.UserURLsResponse.url:type_name -> shortener.URLData
	0, // 1: shortener.ShortenerService.ShortenURL:input_type -> shortener.URLShortenRequest
	2, // 2: shortener.ShortenerService.ExpandURL:input_type -> shortener.URLExpandRequest
	6, // 3: shortener.ShortenerService.ListUserURLs:input_type -> google.protobuf.Empty
	1, // 4: shortener.ShortenerService.ShortenURL:output_type -> shortener.URLShortenResponse
	3, // 5: shortener.ShortenerService.ExpandURL:output_type -> shortener.URLExpandResponse
	4, // 6: shortener.ShortenerService.ListUserURLs:output_type -> shortener.UserURLsResponse
	0, // [0:1] is the sub-list for field type_name
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	1, // [1:4] is the sub-list for method input_type
	4, // [4:7] is the sub-list for method output_type
}

func init() { file_api_shortener_proto_init() }
func file_api_shortener_proto_init() {
	if File_api_shortener_proto != nil {
		return
	}
	// NOTE: Exporter assignments removed to satisfy static analysis.

	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_shortener_proto_goTypes,
		DependencyIndexes: file_api_shortener_proto_depIdxs,
		MessageInfos:      file_api_shortener_proto_msgTypes,
	}.Build()
	File_api_shortener_proto = out.File
	file_api_shortener_proto_rawDesc = nil
	file_api_shortener_proto_goTypes = nil
	file_api_shortener_proto_depIdxs = nil
}
